version: '3.8'

services:
  lv-demo-site:
    build: .
    container_name: lv-demo-site
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
    networks:
      - fairs-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lv-demo.rule=Host(`lv-demo.local`)"
      - "traefik.http.services.lv-demo.loadbalancer.server.port=3007"

  # Reference to main platform (if running standalone)
  fairs-commerce-platform:
    image: fairs-commerce-platform:latest
    container_name: fairs-commerce-platform
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - fairs-network
    profiles:
      - standalone

networks:
  fairs-network:
    driver: bridge
